#!/usr/bin/env bash

set -euo pipefail

whereami="$(dirname "${BASH_SOURCE[0]}")"

status=0
"${whereami}/build-options" || status=1
(
    cd "${whereami}/.." && docker run -i --rm -v "${PWD}:/code" -w /code bats/bats:1.13.0 test
) || status=1
exit $status

