#!/usr/bin/env bash
# shellcheck shell=bash
# shellcheck disable=SC1090,SC1091

# An application specific service to rename Home Assistant backups and copy them off site.
# Copyright (C) 2025 James Hanlon [mailto:jim@hanlonsoftware.com]
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

function ha-offsite-backups() {
    ENV=${ENV:-${HOME:-/root}/.env}
    [[ -r "${ENV}" ]] && source "${ENV}"

    source "${COMMON_FUNCTIONS_FILE:-/usr/local/include/common-functions}"

    set -o errexit -o errtrace -o nounset -o pipefail
    is-true "${DEBUG:-false}" && set -o xtrace -o verbose

    export AWS_CONFIG_FILE="${AWS_CONFIG_FILE:-/run/secrets/aws-config}"
    export AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME:?Need bucket}
    export BACKUP_DIR=${BACKUP_DIR:=/backups}
    export BUCKET=${AWS_S3_BUCKET_NAME}
    export CRON_EXPRESSION="${CRON_EXPRESSION:=@daily}"
    export DEBUG=${DEBUG:=false}
    export DRYRUN=${DRYRUN:=false}

    # Create a work directory
    WORKDIR=$(mktemp -d)
    # shellcheck disable=SC2064
    trap "rm -rf '${WORKDIR}' >/dev/null 2>&1 || true" EXIT
    cd "${WORKDIR}"

    awsargs=--no-progress
    is-true "${DRYRUN}" && awsargs="${awsargs} --dryrun"

    info "begin sync '${BACKUP_DIR}' to S3 bucket '${BUCKET}'"
    # FIXME: Make -name parameter configurable
    uri=s3://${BUCKET}
    found=false
    while IFS= read -r -d '' file; do
        found=true
        object_name=$(xform-backup-name "${file}")
        info "sync '${file}' with '${uri}/${object_name}'"
        ln -s "${file}" "${object_name}"
    done < <(find "${BACKUP_DIR}" -maxdepth 1 -type f -name 'Automatic_backup_*.tar' -print0)
    if [[ "${found}" != true ]]; then
        info "no matching backup files found in '${BACKUP_DIR}'"
    fi
    info "running aws s3 sync ${awsargs} '${WORKDIR}' ${uri}"
    # shellcheck disable=SC2086
    aws s3 sync ${awsargs} "${WORKDIR}" "${uri}" || {
        local rc=$?
        error "aws s3 sync exited with status ${rc}"
    }
    info "completed aws s3 sync ${awsargs} '${WORKDIR}' ${uri}"
    info "finish sync '${BACKUP_DIR}' to S3 bucket '${BUCKET}'"

    exit 0
}

function xform-backup-name() {
    local file=${1:?Need filename}
    # Parse filenames like:
    # Automatic_backup_2025.6.3_2025-07-06_05.35_00004800.tar
    # -> 20250706T053500-home-assistant-automatic-backup-2025.6.3.tar
    # Prefer a regex-based, robust extraction and a safe fallback.
    local f
    f=$(basename -- "${file}")
    local re='^Automatic_backup_([^_]+)_([0-9]{4}-[0-9]{2}-[0-9]{2})_([0-9]{2}\.[0-9]{2})_([0-9]+)\.([^.]+)$'
    if [[ "${f}" =~ ${re} ]]; then
        local release="${BASH_REMATCH[1]}"
        local date="${BASH_REMATCH[2]}"
        local time="${BASH_REMATCH[3]}"
        local nanos="${BASH_REMATCH[4]}"
        local ext="${BASH_REMATCH[5]}"
        local base
        base="automatic-backup-${release,,}"
        base="${base//_/-}"
        local date_nodash="${date//-/}"
        local time_nodot="${time//./}"
        local seconds="${nanos:0:2}"
        local time_full="${time_nodot}${seconds}"
        printf "%sT%s-home-assistant-%s.%s" "${date_nodash}" "${time_full}" "${base}" "${ext}"
    else
        # Fallback to original heuristic when regex doesn't match.
        local ext_fallback="${f##*.}"
        local base_fallback
        base_fallback=$(echo "${f}" | cut -d_ -f-3 | tr '[:upper:]' '[:lower:]' | tr '_' '-')
        local date_fallback
        date_fallback=$(echo "${f}" | cut -d_ -f4 | tr -d '-')
        local time_fallback
        time_fallback=$(echo "${f}" | cut -d_ -f5- | tr -d '._' | cut -c -6)
        printf "%sT%s-home-assistant-%s.%s" "${date_fallback}" "${time_fallback}" "${base_fallback}" "${ext_fallback}"
    fi
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    ha-offsite-backups "$@"
fi