#!/usr/bin/env bash
# shellcheck shell=bash
# shellcheck disable=SC1090,SC1091

# An application specific service to rename Home Assistant backups and copy them off site.
# Copyright (C) 2025 James Hanlon [mailto:jim@hanlonsoftware.com]
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

source "${COMMON_FUNCTIONS_FILE:-/usr/local/include/common-functions}"

set -o errexit -o errtrace -o nounset -o pipefail
set +o xtrace +o verbose
if is_true "${DEBUG:-false}"; then
    set -o xtrace -o verbose
fi

ENV=${ENV:-${HOME:-/root}/.env}
# shellcheck disable=SC1090
[[ -r "${ENV}" ]] && source "${ENV}"

# Write cronjob env to file, fill in sensible defaults, and read them back in
install -m 0600 /dev/null "${ENV}"
cat <<EOF >"${ENV}"
export AWS_CONFIG_FILE='${AWS_CONFIG_FILE:-/run/secrets/aws-config}'
export AWS_S3_BUCKET_NAME='${AWS_S3_BUCKET_NAME:?Need bucket}'
export BACKUP_DIR='${BACKUP_DIR:-/backups}'
export CRON_EXPRESSION='${CRON_EXPRESSION:-@daily}'
export DEBUG='${DEBUG:-false}'
export DRYRUN='${DRYRUN:-false}'
EOF
info "create env file ${ENV}"
info < "${ENV}"
# shellcheck disable=SC1090
source "${ENV}"

# Add our cron entry, and direct stdout & stderr to Docker commands stdout
COMMAND=${COMMAND:-/usr/local/bin/ha-offsite-backups}
info "installing cron.d entry: ${COMMAND}"
_crontab="/var/spool/cron/crontabs/$(id -un)"
echo "${CRON_EXPRESSION} ${COMMAND} 2>&1" > "${_crontab}" && chmod -c 0600 "${_crontab}" | info
info "crontab: $(cat "${_crontab}")"

info "handing the reins over to cron daemon"
exec crond -l 2 -f

